<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>br.vituz.core</groupId>
        <artifactId>vlogin-parent</artifactId>
        <version>1.1.0</version>
    </parent>

    <artifactId>vlogin-bungee</artifactId>
    <name>vLogin BungeeCord</name>

    <dependencies>
        <dependency>
            <groupId>br.vituz.core</groupId>
            <artifactId>vlogin-common</artifactId>
        </dependency>
        <dependency>
            <groupId>net.md-5</groupId>
            <artifactId>bungeecord-api</artifactId>
            <version>${bungee.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
